---

- name: Incluir fichero
  ansible.builtin.lineinfile:
    path: /etc/named.conf
    line: 'include "/etc/named/named.conf.local";'


- name: Copiar fichero /etc/named/named.conf.local
  ansible.builtin.template:
    src: named.conf.local
    dest: /etc/named/named.conf.local
    owner: root
    group: named
    mode: '0644'
  notify: Reiniciar servicio Debian  


- name: Comprobar sintaxis fichero /etc/named/named.conf.local
  ansible.builtin.command:
    cmd: named-checkconf /etc/named/named.conf.local
  register: local
  failed_when: local.changed == "false"
  changed_when: false


- name: Debug /etc/named/named.conf.local
  ansible.builtin.debug:
    msg: "{{ local.stdout_lines }}"
  failed_when: local.rc == 1
  when: local.rc == 1


- name: Copiar fichero zona directa
  ansible.builtin.template:
    src: fichero_zona_directa
    dest: /var/named/{{ file_directo }}
    owner: root
    group: named
    mode: '0644'
  notify: Reiniciar servicio Debian


- name: Comprobar sintaxis fichero zona directa
  ansible.builtin.command:
    cmd: named-checkzone {{ dominio_directo }} /var/named/{{ file_directo }}
  register: directo
  failed_when: directo.changed == "false"
  changed_when: false


- name: Debug fichero zona directa
  ansible.builtin.debug:
    msg: "{{ directo.stdout_lines }}"
  failed_when: directo.rc == 1
  when: directo.rc == 1


- name: Copiar fichero zona inversa
  ansible.builtin.template:
    src: fichero_zona_inversa
    dest: /var/named/{{ file_inverso }}
    owner: root
    group: named
    mode: '0644'
  notify: Reiniciar servicio Debian


- name: Comprobar sintaxis fichero zona inversa
  ansible.builtin.command:
    cmd: named-checkzone {{ dominio_inverso }} /var/named/{{ file_inverso }}
  register: inverso
  failed_when: inverso.changed == "false"
  changed_when: false


- name: Debug fichero zona inverso
  ansible.builtin.debug:
    msg: "{{ inverso.stdout_lines }}"
  failed_when: inverso.rc == 1
  when: inverso.rc == 1   

...